[build]
  command = "npm run build"
  publish = "dist"
[build.environment]
  REACT_APP_TWILIO_ACCOUNT_SID = "YOUR_SID"
  REACT_APP_TWILIO_AUTH_TOKEN  = "YOUR_TOKEN"
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
