[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_TWILIO_ACCOUNT_SID = ""
  REACT_APP_TWILIO_AUTH_TOKEN = ""

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
